### PR TITLE
Implement true row props

### PR DESCRIPTION
**Pull request by joneit**
See issue #647. ~This PR is tentative based on performance impact.~ _Code has now gone through several rounds of testing/tweaking for performance. Performance checks out; please proceed with review._

### CODE REVIEW

**Comment by nmichaud** [comment]
What's the difference between this and #640?

**Comment by joneit** [comment]
@nmichaud Whoops forgot to push the 2nd commit; it's pushed now

**Comment by joneit** [comment]
Rebased ("2nd commit" is now the only commit).

**Comment by joneit** [comment]
As a side note:

It would be nice if Hypergrid had a property to specify the properties hierarchy because I can see how some apps would prefer a different order, for example:
> grid ← row ← column ← cell

Unfortunately, this is not possible in a performant way due to the current design. However it may be possible in a future version if we can address the design issue.

**Comment by joneit** [comment]
I did some performance profiles and performance is not measurably impacted, which is great.

Deprecated `grid.properties.rowProperties` (with a warning) in favor of a better name `stripes` because we now have true row properties and this was now confusing.

Implemented following new properties, defaulted to `true`, which if set to `false` will disable rendering the related properties, significantly improving performance.
* `renderColumnProps`
* `renderStripes`
* `renderRowProps`
* `renderCellProps`

I also isolated the logic for layering properties during rendering into a new method `grid.renderer.configurator` so that developer can override it with different or faster logic.

**Comment by joneit** [comment]
@Dwaynekj @dcchuck @nmichaud @neilslinger @texodus @stevewirts Success! This PR passed performance tests so it's definitely a go, so _**please review.**_

Note that row properties api is simpler and shorter cell properties api — which we could consider simplifying as well.

**Comment by Dwaynekj** [comment]
@joneit what Browsers and OS did you test? Chrome 40 is in that list?

**Comment by joneit** [comment]
@Dwaynekj Good point. I'll test in Chrome 40. But this can still go because of the props and the overridable method:
* If impactful to Chrome 40l, I'll try setting `grid.properties.renderRowProps = false` to skip the logic ([the line]() I called out in previous comment).
   * If better, we can consider making that the default? ...although upgrading to v3.0.0 is going to require some code tweaks anyway and setting this prop to `false` but I hesitate doing that for the relatively few Chrome 40 users; rather it could be a "recommended Chrome 40 tweak."
* If still impactful, we can supply a simpler `configurator` akin to the original logic (by eliding that line entirely).
   * Again, we could consider making that the default, but again that setting could be a recommended Chrome 40 tweak.

**Comment by stevewirts** [comment]
I WILL be there at 330 today

**Comment by joneit** [comment]
## Layering prop classes in any order

I've re-pushed this PR with new logic to select prop classes to render and in which order. Overcame some performance-related issues to do this. 

### Performance checks out!
I did some performance profiles and performance is not measurably impacted, which is great.

There is still one case where performance takes a hit (when column props are omitted; see below). 

### Renamed property: `rowProperties` → `stripes`
Deprecated `grid.properties.rowProperties` (with a warning) in favor of a better name `stripes` because we now have true row properties and this was now confusing.

### New property: `cellEvent.prototype.rowProperties`
This is a new getter/setter ([example](https://github.com/fin-hypergrid/core/pull/648/files#diff-5a077d9e9d2adeca2bd0274d0a40ed5dR1242)).

The logic layers the property classes in the order defined in `Hypergrid.properties` (aka `require('defaults.js')`):
```js
propClassLayers: [ 'columns',  'stripes',  'rows',  'cells' ]
```
In addition to the above grid default, the tree and row handle columns both override the grid property ([actual code](https://github.com/fin-hypergrid/core/pull/648/files#diff-efa8c1cff4b1c772c558c7576aa52fd0R174)):
```js
treeColumnProperties.propClassLayers = rowColumnProperties.propClassLayers = ['columns'];
```
The above only renders the column props, thus preventing row stripes from rendering in those columns.

### Example
So the default is to override column props with row props. To override this default to render column props on top of row props:
```js
grid.properties.propClassLayers = ['rows', 'columns'];
```

### New overridable method: `grid.renderer.assignProps`
The layering logic is isolated in a [new method](https://github.com/fin-hypergrid/core/pull/648/files#diff-5a077d9e9d2adeca2bd0274d0a40ed5dR1239) which developers can override with alternative or faster logic.

**Comment by joneit** [comment]
Rebased to develop post merge of #661.

**Comment by joneit** [comment]
@dcchuck do give me a call if you'd like a demo and/or walk-thru!

**Comment by joneit** [comment]
@nmichaud @dcchuck @Dwaynekj @neilslinger Code has now gone through several rounds of testing/tweaking for performance. Performance checks out. We need at least one review (better would be two) from you guys.... thanks!

**Comment by joneit** [comment]
Rebased to develop.

**Comment by joneit** [comment]
Rebased to `develop` required after merging #666, #674, and #676.

**Pull request merged**
