### PR TITLE
Prepare release candidate 2.1.0

### PR DESCRIPTION
**Pull request by joneit**
RC prep checklist:
- [x] clean-up commits:
   - [x] renamed `stripes` prop to `rowStripes` (formerly `rowProperties`)
   - [x] renamed `fixedLineColor`, `fixedLineWidth`, and `fixedEdgeWidth` -> `fixedLines.color`, `fixedLines.width`, and `fixedLines.edge` (respectively)
- [x] a catch-up commit for the edits made to master subsequent to develop and master diverging. Master had a few edits to several `.md` (markdown) files as well as edits to a few comments, etc.
- [x] bump version number
- [x] release notes _(completed!)_

### CODE REVIEW

**Comment by joneit** [comment]
@nmichaud You can use this branch `joneit/prepare-release-candidate-2.1.0` for alpha testing (until we merge to a proper `upstream/alpha` branch). This branch contains one essential fix needed by my ~`joneit/omni`~ branch (now deleted).

**Comment by joneit** [comment]
@nmichaud FYI, I changed the default fixed/scrolling rule line width back to 2 (instead of 3) and at the same time I used the (new) color property to make it slightly darker (from `#c7c7c7` to `#a4a4a4`), which I think looks pretty good. Of course, these are just defaults: You will need to adjust (at least) the color, anyway.

**Comment by Dwaynekj** [comment]
@joneit Can you please confirm that the build is working

**Comment by joneit** [comment]
@Dwaynekj No build was posted, but if you meant building it yourself, then Yes, the build is working:
```
git remote add joneit https://github.com/joneit/core.git
git fetch joneit prepare-release-candidate-2.1.0
git checkout joneit/prepare-release-candidate-2.1.0
npm install
gulp build
```
I will post a build file on `fin-hypergrid.github.io`.

**Comment by joneit** [comment]
@nmichaud @Dwaynekj @dcchuck @neilslinger 
I've posted build files for you convenience so you don't have to build it yourself:
```
https://fin-hypergrid.github.io/core/2.1.0-alpha/build/fin-hypergrid.js
https://fin-hypergrid.github.io/core/2.1.0-alpha/build/fin-hypergrid.min.js
```
I look forward to any feedback you may have.

**Comment by joneit** [comment]
@Dwaynekj 
FYI, I'm using:
* node 8.9.2
* npm 5.6.0

Please let me know if the build is not working for you.

**Comment by joneit** [comment]
## Regression 1
Scrolling to bottom goes beyond the end of the grid. That is, the last row scrolls up to the top leaving white space. In current release ([2.0.2](https://fin-hypergrid.github.io/core/2.0.2/)) scrolling stopped with last row perfectly at bottom.

**Comment by joneit** [comment]
@nmichaud @neilslinger @Dwaynekj @dcchuck Please note:
* I have completed the release notes. Please refer to issue #679.
* In particular note there should be _no breaking changes_ with this release.
* I am so far aware of only one regression, noted above. This is not critical and I feel we can address this later (after release).
* DJ, we never discussed the import of not passing `treeColumnIndex` and `rowColumnIndex` to the data source constructor. The question is, will this break anything?
* I will update the build file previously posted (see above) for your testing purposes so that it now include the most recent commits above (minor improvements and renaming a couple of things).

**Comment by joneit** [comment]
@nmichaud Added that final commit for tree column fix. Please review & re-approve. thx

**Pull request merged**
